services:
  duplicati:
    image: ${DOCKER_MIRROR}lscr.io/linuxserver/duplicati:${VERSION}
    container_name: duplicati
    ports:
      - "${TRIM_SERVICE_PORT}:8200"
    volumes:
      - ${TRIM_PKGVAR:?}/config:/config
      - ${BACKUP_SOURCE:-/vol1}:/source:ro
      - ${TRIM_PKGVAR:?}/backups:/backups
    environment:
      - TZ=Asia/Shanghai
      - PUID=${TRIM_UID}
      - PGID=${TRIM_GID}
    restart: unless-stopped
