services:
  surveyking:
    image: ${DOCKER_MIRROR}docker.io/surveyking/surveyking:v${VERSION}
    container_name: surveyking
    ports:
      - "${TRIM_SERVICE_PORT}:1991"
    volumes:
      - ${TRIM_PKGVAR:?}/db:/app/db
      - ${TRIM_PKGVAR:?}/files:/app/files
      - ${TRIM_PKGVAR:?}/logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
