services:
  ombi:
    image: ${DOCKER_MIRROR}docker.io/linuxserver/ombi:${VERSION}
    container_name: ombi
    ports:
      - "${TRIM_SERVICE_PORT}:3579"
    volumes:
      - ${TRIM_PKGVAR:?}/config:/config
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
