#!/bin/bash

is_docker_running() {
    docker inspect penpot-frontend | grep -q '"Status": "running",' || exit 1
}

case $1 in
start) exit 0 ;;
stop) exit 0 ;;
status) if is_docker_running; then exit 0; else exit 3; fi ;;
*) exit 1 ;;
esac
