services:
  node-red:
    image: ${DOCKER_MIRROR}docker.io/nodered/node-red:${VERSION}
    container_name: node-red
    ports:
      - "${TRIM_SERVICE_PORT}:1880"
    volumes:
      - ${TRIM_PKGVAR:?}/data:/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
