services:
  penpot-frontend:
    image: ${DOCKER_MIRROR}docker.io/penpotapp/frontend:${VERSION}
    container_name: penpot-frontend
    depends_on:
      - penpot-backend
    ports:
      - "${TRIM_SERVICE_PORT}:80"
    volumes:
      - ${TRIM_PKGVAR}/assets:/opt/data/assets
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped

  penpot-backend:
    image: ${DOCKER_MIRROR}docker.io/penpotapp/backend:${VERSION}
    container_name: penpot-backend
    depends_on:
      - penpot-db
      - penpot-redis
    environment:
      - TZ=Asia/Shanghai
      - PENPOT_DATABASE_URI=postgresql://penpot:penpot@penpot-db:5432/penpot
      - PENPOT_REDIS_URI=redis://penpot-redis:6379/0
      - PENPOT_SECRET_KEY=${PENPOT_SECRET_KEY}
      - PENPOT_PUBLIC_URI=${PENPOT_PUBLIC_URI}
    restart: unless-stopped

  penpot-exporter:
    image: ${DOCKER_MIRROR}docker.io/penpotapp/exporter:${VERSION}
    container_name: penpot-exporter
    depends_on:
      - penpot-frontend
    environment:
      - TZ=Asia/Shanghai
      - PENPOT_PUBLIC_URI=${PENPOT_PUBLIC_URI}
    restart: unless-stopped

  penpot-db:
    image: ${DOCKER_MIRROR}docker.io/postgres:15-alpine
    container_name: penpot-db
    volumes:
      - ${TRIM_PKGVAR}/db:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot
    restart: unless-stopped

  penpot-redis:
    image: ${DOCKER_MIRROR}docker.io/redis:7-alpine
    container_name: penpot-redis
    volumes:
      - ${TRIM_PKGVAR}/redis:/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
