services:
  clamav:
    image: ${DOCKER_MIRROR}docker.io/clamav/clamav:${VERSION}
    container_name: clamav
    ports:
      - "${TRIM_SERVICE_PORT}:3310"
    volumes:
      - ${TRIM_PKGVAR}/virus_db:/var/lib/clamav
      - ${TRIM_PKGVAR}/config:/etc/clamav
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
