services:
  sunshine:
    image: ${DOCKER_MIRROR}lscr.io/linuxserver/sunshine:${VERSION}
    container_name: sunshine
    ports:
      - "${TRIM_SERVICE_PORT}:47990"
      - "47984-47989:47984-47989/tcp"
      - "48010:48010/tcp"
      - "47998-48000:47998-48000/udp"
      - "48002:48002/udp"
      - "48010:48010/udp"
    volumes:
      - ${TRIM_PKGVAR}/config:/config
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=Asia/Shanghai
      - PUID=${TRIM_UID}
      - PGID=${TRIM_GID}
    restart: unless-stopped
