services:
  n8n:
    image: ${DOCKER_MIRROR}docker.n8n.io/n8nio/n8n:${VERSION}
    container_name: n8n
    ports:
      - "${TRIM_SERVICE_PORT}:5678"
    volumes:
      - ${TRIM_PKGVAR}/data:/home/node/.n8n
    environment:
      - TZ=Asia/Shanghai
      - GENERIC_TIMEZONE=Asia/Shanghai
    restart: unless-stopped
