services:
  jellystat:
    image: ${DOCKER_MIRROR}docker.io/cyfershepard/jellystat:${VERSION}
    container_name: jellystat
    depends_on:
      - jellystat-db
    ports:
      - "${TRIM_SERVICE_PORT}:3000"
    volumes:
      - ${TRIM_PKGVAR}/data:/app/backend/db
    environment:
      - TZ=Asia/Shanghai
      - JS_BASE_URL=/
      - POSTGRES_IP=jellystat-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=jellystat
      - POSTGRES_PASSWORD=jellystat_pass
      - JWT_SECRET=fnos-jellystat-secret
    restart: unless-stopped

  jellystat-db:
    image: ${DOCKER_MIRROR}docker.io/postgres:16
    container_name: jellystat-db
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=jellystat
      - POSTGRES_PASSWORD=jellystat_pass
      - POSTGRES_DB=jellystat
    volumes:
      - ${TRIM_PKGVAR}/db:/var/lib/postgresql/data
    restart: unless-stopped
