services:
  komga:
    image: ${DOCKER_MIRROR}docker.io/gotson/komga:${VERSION}
    container_name: komga
    ports:
      - "${TRIM_SERVICE_PORT}:25600"
    volumes:
      - ${TRIM_PKGVAR}/config:/config
      - ${TRIM_PKGVAR}/data:/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
