services:
  pihole:
    image: ${DOCKER_MIRROR}docker.io/pihole/pihole:${VERSION}
    container_name: pihole
    ports:
      - "${TRIM_SERVICE_PORT}:80"
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ${TRIM_PKGVAR:?}/etc-pihole:/etc/pihole
      - ${TRIM_PKGVAR:?}/etc-dnsmasq.d:/etc/dnsmasq.d
    environment:
      - TZ=Asia/Shanghai
      - WEBPASSWORD=${PIHOLE_PASSWORD:-admin}
      - WEB_PORT=80
    restart: unless-stopped
