services:
  seerr:
    image: ${DOCKER_MIRROR}docker.io/seerrteam/seerr:${VERSION}
    container_name: seerr
    ports:
      - "${TRIM_SERVICE_PORT}:5055"
    volumes:
      - ${TRIM_PKGVAR:?}/config:/app/config
    environment:
      - TZ=Asia/Shanghai
      - LOG_LEVEL=info
    restart: unless-stopped
