#!/bin/bash

service_postinst() {
    mkdir -p "${TRIM_PKGVAR}/data" 2>/dev/null || true
    mkdir -p "${TRIM_PKGVAR}/lib" 2>/dev/null || true
    mkdir -p "${TRIM_PKGVAR}/cache" 2>/dev/null || true
}
