services:
  glances:
    image: ${DOCKER_MIRROR}docker.io/nicolargo/glances:${VERSION}
    container_name: glances
    pid: host
    ports:
      - "${TRIM_SERVICE_PORT}:61208"
    volumes:
      - ${TRIM_PKGVAR}/config:/etc/glances
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Asia/Shanghai
      - GLANCES_OPT=-w
    restart: unless-stopped
