services:
  copyparty:
    image: ${DOCKER_MIRROR}docker.io/copyparty/ac:${VERSION}
    container_name: copyparty
    ports:
      - "${TRIM_SERVICE_PORT}:3923"
    volumes:
      - ${TRIM_PKGVAR}/data:/w
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
