services:
  dpanel:
    image: ${DOCKER_MIRROR}docker.io/dpanel/dpanel:${VERSION}
    container_name: dpanel
    ports:
      - "${TRIM_SERVICE_PORT}:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRIM_PKGVAR:?}/data:/dpanel
    environment:
      - TZ=Asia/Shanghai
      - APP_NAME=dpanel
    restart: unless-stopped
