services:
  melodyhub:
    image: ${DOCKER_MIRROR}docker.io/geelonn/melodyhub:v${VERSION}
    container_name: melody-hub
    ports:
      - "${TRIM_SERVICE_PORT}:3000"
    volumes:
      - ${TRIM_PKGVAR:?}/data:/app/data
      - ${TRIM_PKGVAR:?}/music:/app/music
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATA_DIR=/app/data
      - MUSIC_DIR=/app/music
      - TZ=Asia/Shanghai
    restart: unless-stopped
