services:
  ente:
    image: ${DOCKER_MIRROR}ghcr.io/ente-io/server:${VERSION}
    container_name: ente
    depends_on:
      - ente-db
      - ente-minio
    ports:
      - "${TRIM_SERVICE_PORT}:8080"
    volumes:
      - ${TRIM_PKGVAR}/data:/data
    environment:
      - ENTE_DB_HOST=ente-db
      - ENTE_DB_PORT=5432
      - ENTE_DB_NAME=ente
      - ENTE_DB_USER=ente
      - ENTE_DB_PASSWORD=ente
    restart: unless-stopped

  ente-db:
    image: ${DOCKER_MIRROR}docker.io/postgres:15-alpine
    container_name: ente-db
    volumes:
      - ${TRIM_PKGVAR}/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ente
      - POSTGRES_PASSWORD=ente
      - POSTGRES_DB=ente
    restart: unless-stopped

  ente-minio:
    image: ${DOCKER_MIRROR}docker.io/minio/minio:latest
    container_name: ente-minio
    command: server /data
    volumes:
      - ${TRIM_PKGVAR}/minio:/data
    environment:
      - MINIO_ROOT_USER=ente
      - MINIO_ROOT_PASSWORD=ente-minio-secret
    restart: unless-stopped
