services:
  appflowy:
    image: ${DOCKER_MIRROR}docker.io/appflowyinc/appflowy_cloud:${VERSION}
    container_name: appflowy
    ports:
      - "${TRIM_SERVICE_PORT}:8025"
    volumes:
      - ${TRIM_PKGVAR:?}/data:/app/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
