services:
  koodo-reader:
    image: ${DOCKER_MIRROR}ghcr.io/koodo-reader/koodo-reader:master
    container_name: koodo-reader
    ports:
      - "${TRIM_SERVICE_PORT}:80"
    volumes:
      - ${TRIM_PKGVAR:?}/uploads:/app/uploads
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
