services:
  localai:
    image: ${DOCKER_MIRROR}docker.io/localai/localai:${VERSION}-cpu
    container_name: localai
    ports:
      - "${TRIM_SERVICE_PORT}:8080"
    volumes:
      - ${TRIM_PKGVAR}/models:/build/models
    environment:
      - TZ=Asia/Shanghai
      - THREADS=4
      - CONTEXT_SIZE=512
    restart: unless-stopped
