services:
  open-webui:
    image: ${DOCKER_MIRROR}docker.io/openwebui/open-webui:${VERSION}
    container_name: open-webui
    ports:
      - "${TRIM_SERVICE_PORT}:8080"
    volumes:
      - ${TRIM_PKGVAR}/data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://172.17.0.1:11434
      - WEBUI_SECRET_KEY=fnos-secret-key
      - ENABLE_SIGNUP=true
      - TZ=Asia/Shanghai
    restart: unless-stopped
