services:
  netbird:
    image: ${DOCKER_MIRROR}docker.io/netbirdio/netbird:${VERSION}
    container_name: netbird
    cap_add:
      - NET_ADMIN
      - SYS_RESOURCE
    volumes:
      - ${TRIM_PKGVAR}/config:/etc/netbird
    environment:
      - TZ=Asia/Shanghai
      - NB_SETUP_KEY=${NB_SETUP_KEY:-}
    network_mode: host
    restart: unless-stopped
