services:
  mattermost:
    image: ${DOCKER_MIRROR}docker.io/mattermost/mattermost-team-edition:${VERSION}
    container_name: mattermost
    depends_on:
      - mattermost-db
    ports:
      - "${TRIM_SERVICE_PORT}:8065"
    volumes:
      - ${TRIM_PKGVAR:?}/config:/mattermost/config
      - ${TRIM_PKGVAR:?}/data:/mattermost/data
      - ${TRIM_PKGVAR:?}/logs:/mattermost/logs
      - ${TRIM_PKGVAR:?}/plugins:/mattermost/plugins
    environment:
      - TZ=Asia/Shanghai
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mattermost:mattermost@mattermost-db:5432/mattermost?sslmode=disable
    restart: unless-stopped

  mattermost-db:
    image: ${DOCKER_MIRROR}docker.io/postgres:15-alpine
    container_name: mattermost-db
    volumes:
      - ${TRIM_PKGVAR:?}/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mattermost
      - POSTGRES_PASSWORD=mattermost
      - POSTGRES_DB=mattermost
    restart: unless-stopped
