services:
  rocketchat:
    image: ${DOCKER_MIRROR}docker.io/rocketchat/rocket.chat:${VERSION}
    container_name: rocketchat
    ports:
      - "${TRIM_SERVICE_PORT}:3000"
    volumes:
      - ${TRIM_PKGVAR:?}/uploads:/app/uploads
    environment:
      - TZ=Asia/Shanghai
      - MONGO_URL=mongodb://rocketchat-mongo:27017/rocketchat?replicaSet=rs0
      - MONGO_OPLOG_URL=mongodb://rocketchat-mongo:27017/local?replicaSet=rs0
      - ROOT_URL=http://localhost:3000
      - PORT=3000
      - DEPLOY_METHOD=docker
    depends_on:
      - rocketchat-mongo
    restart: unless-stopped

  rocketchat-mongo:
    image: ${DOCKER_MIRROR}docker.io/bitnami/mongodb:8.0
    container_name: rocketchat-mongo
    environment:
      - TZ=Asia/Shanghai
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_HOST=rocketchat-mongo
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_ADVERTISED_HOSTNAME=rocketchat-mongo
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ${TRIM_PKGVAR:?}/mongodb:/bitnami/mongodb
    restart: unless-stopped
