services:
  sabnzbd:
    image: ${DOCKER_MIRROR}docker.io/linuxserver/sabnzbd:${VERSION}
    container_name: sabnzbd
    ports:
      - "${TRIM_SERVICE_PORT}:8080"
    volumes:
      - ${TRIM_PKGVAR}/config:/config
      - ${TRIM_PKGVAR}/downloads:/downloads
      - ${TRIM_PKGVAR}/incomplete:/incomplete-downloads
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
