#!/bin/bash

LOG_FILE="${TRIM_PKGVAR}/${TRIM_APPNAME}.log"
PID_FILE="${TRIM_PKGVAR}/${TRIM_APPNAME}.pid"

APP_DIR="${TRIM_APPDEST}"
APP_DATA_DIR="${TRIM_PKGVAR}"

SERVICE_COMMAND="$APP_DIR/bin/easytier-server $APP_DATA_DIR"
SVC_BACKGROUND=y
SVC_WRITE_PID=y

service_postinst() {
    mkdir -p "${APP_DATA_DIR}/data" "${APP_DATA_DIR}/logs"
}

service_preuninst() {
    pkill -x "easytier-web-embed" 2>/dev/null || true
    sleep 1
    pkill -9 -x "easytier-web-embed" 2>/dev/null || true
}

service_poststop() {
    service_preuninst
}
