services:
  puter:
    image: ghcr.io/heyputer/puter:${VERSION}
    container_name: puter
    ports:
      - "${TRIM_SERVICE_PORT}:4100"
    volumes:
      - ${TRIM_PKGVAR:?}/config:/etc/puter
      - ${TRIM_PKGVAR:?}/data:/var/puter
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
